Resources:
  VPCPeering1:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      VpcId: !Ref VPC1
      PeerVpcId: !Ref VPC2

  VPCPeering2:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      VpcId: !Ref VPC2
      PeerVpcId: !Ref VPC3

  VPCPeering3:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      VpcId: !Ref VPC1
      PeerVpcId: !Ref VPC3
