AWSTemplateFormatVersion: '2010-09-09'
Description: Configuración del sistema de archivos EFS

Resources:
  FileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      PerformanceMode: generalPurpose
      Encrypted: true
      FileSystemTags:
        - Key: Name
          Value: API-EFS

  MountTarget:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystem
      SubnetId: !Ref SubnetId
      SecurityGroups:
        - !Ref SecurityGroupId

Outputs:
  FileSystemId:
    Value: !Ref FileSystem
