AWSTemplateFormatVersion: '2010-09-09'
Description: Balanceador de carga HAProxy

Resources:
  HAProxyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0f9575d3d509bae0c
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref SecurityGroupId
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y haproxy
          echo "frontend http_front
            bind *:80
            default_backend servers
          
          backend servers
            balance roundrobin
            server web1 ${WebServer1PrivateIP}:5000 check
            server web2 ${WebServer2PrivateIP}:5000 check" > /etc/haproxy/haproxy.cfg
          systemctl enable haproxy
          systemctl start haproxy

Outputs:
  HAProxyInstanceId:
    Value: !Ref HAProxyInstance
