AWSTemplateFormatVersion: '2010-09-09'
Description: VPC y Subnet para la API REST

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: API-VPC

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: us-east-1a
      Tags:
        - Key: Name
          Value: API-Subnet

Outputs:
  VPCId:
    Value: !Ref VPC
  SubnetId:
    Value: !Ref PublicSubnet
